import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../components/Header';
import LeftSideBar from '../components/LeftSideBar';
import MainSection from '../components/MainSection';
import RightSideBar from '../components/RightSideBar';

const Home: NextPage = () => {
	return (
		<div className="bg-gray-100 dark:bg-dark-main relative">
			<Head>
				<title>Facebook Clone</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<main className="pt-5 relative">
				{/* left side bar */}
				<LeftSideBar />

				{/* right side bar */}
				<RightSideBar />

				{/* main */}
				<MainSection />
			</main>
		</div>
	);
};

export default Home;
